#!/usr/bin/env bash
set -e

INSTALL_DIR="${HOME}/.local/bin"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/wt-feature"
REPO_URL="https://raw.githubusercontent.com/crobbo/wt-feature/master"

echo "wt-feature installer"
echo "===================="
echo ""

# Create directories
mkdir -p "$INSTALL_DIR"
mkdir -p "$CONFIG_DIR"

# Download the script
echo "Downloading wt-feature..."
curl -fsSL "$REPO_URL/wt-feature.sh" -o "$INSTALL_DIR/wt-feature.sh"
chmod +x "$INSTALL_DIR/wt-feature.sh"

# Interactive configuration
echo ""
echo "Configuration (press Enter to skip any option)"
echo "-----------------------------------------------"

read -p "Worktrees directory (leave empty for <repo>-worktrees beside your repo): " worktrees_dir

read -p "Files to copy to new worktrees (space-separated, e.g., 'config/master.key .env'): " files_to_copy

read -p "Setup commands to run (e.g., 'bundle install && yarn install'): " setup_commands

# Write config
cat > "$CONFIG_DIR/config" << CONF
# wt-feature configuration
# Generated by installer on $(date)

# Where to create worktrees
# (default: if repo is ~/projects/myapp, worktrees go in ~/projects/myapp-worktrees)
WT_WORKTREES_DIR="${worktrees_dir}"

# Files to copy from main repo (space-separated)
WT_FILES_TO_COPY="${files_to_copy}"

# Commands to run after creating worktree
WT_SETUP_COMMANDS="${setup_commands}"
CONF

echo ""
echo "Config saved to: $CONFIG_DIR/config"

# Detect shell and add source line
add_to_shell_config() {
  local rc_file="$1"
  local source_line="source \"$INSTALL_DIR/wt-feature.sh\""
  
  if [[ -f "$rc_file" ]]; then
    if ! grep -qF "wt-feature.sh" "$rc_file"; then
      echo "" >> "$rc_file"
      echo "# wt-feature - git worktree helper" >> "$rc_file"
      echo "$source_line" >> "$rc_file"
      echo "Added to $rc_file"
      return 0
    else
      echo "Already in $rc_file"
      return 0
    fi
  fi
  return 1
}

echo ""
echo "Adding to shell config..."

added=false
if [[ "$SHELL" == *"zsh"* ]] || [[ -f "$HOME/.zshrc" ]]; then
  add_to_shell_config "$HOME/.zshrc" && added=true
fi

if [[ "$SHELL" == *"bash"* ]] || [[ -f "$HOME/.bashrc" ]]; then
  add_to_shell_config "$HOME/.bashrc" && added=true
fi

if [[ "$added" == false ]]; then
  echo ""
  echo "Could not detect shell config. Add this line manually:"
  echo "  source \"$INSTALL_DIR/wt-feature.sh\""
fi

echo ""
echo "Installation complete!"
echo ""
echo "Restart your shell or run:"
echo "  source \"$INSTALL_DIR/wt-feature.sh\""
echo ""
echo "Then use: wt-feature <branch-name>"
